services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: detalent
      POSTGRES_PASSWORD: detalent
      PGDATA: /data/postgres
      POSTGRES_DB: detalent_dev
    volumes:
      - db:/data/postgres
    ports:
      - "55432:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  db:
    driver: bridge

volumes:
  db:
